// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Generates recipes based on a list of ingredients.
 *
 * - generateRecipes - A function that generates a list of recipes from ingredients.
 * - GenerateRecipesInput - The input type for the generateRecipes function.
 * - GenerateRecipesOutput - The return type for the generateRecipes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecipesInputSchema = z.object({
  ingredients: z
    .array(z.string())
    .describe('A list of ingredients identified from the photo.'),
});
export type GenerateRecipesInput = z.infer<typeof GenerateRecipesInputSchema>;

const GenerateRecipesOutputSchema = z.object({
  recipes: z.array(
    z.object({
      title: z.string().describe('The creative and appealing title of the recipe.'),
      description: z.string().describe('A short, enticing description of the dish, highlighting its unique flavors and appeal.'),
      ingredients: z.array(z.string()).describe('The list of ingredients required for the recipe.'),
      instructions: z.string().describe('Clear, concise, and easy-to-follow instructions for preparing the recipe.'),
    })
  ).describe('A list of unique and tasty recipes generated from the given ingredients.'),
});
export type GenerateRecipesOutput = z.infer<typeof GenerateRecipesOutputSchema>;

export async function generateRecipes(input: GenerateRecipesInput): Promise<GenerateRecipesOutput> {
  return generateRecipesFlow(input);
}

const generateRecipesPrompt = ai.definePrompt({
  name: 'generateRecipesPrompt',
  input: {schema: GenerateRecipesInputSchema},
  output: {schema: GenerateRecipesOutputSchema},
  prompt: `You are a culinary artist, a world-renowned chef celebrated for your innovative, mouth-watering, and unique recipes. Your specialty is turning everyday ingredients into extraordinary culinary experiences.

Given the following list of ingredients, your task is to craft a selection of appealing, unique, and delicious recipes. These recipes should be suitable for a home cook but have a touch of gourmet flair.

For each recipe, provide:
1. A creative and appealing title.
2. A short, enticing description that makes the dish sound irresistible.
3. A complete list of ingredients needed.
4. Clear, step-by-step instructions that are easy to follow.

Focus on creating recipes that are not just standard or boring, but are genuinely exciting and make the best use of the provided ingredients.

Ingredients available:
{{#each ingredients}}- {{{this}}}
{{/each}}`,
});

const generateRecipesFlow = ai.defineFlow(
  {
    name: 'generateRecipesFlow',
    inputSchema: GenerateRecipesInputSchema,
    outputSchema: GenerateRecipesOutputSchema,
  },
  async input => {
    const {output} = await generateRecipesPrompt(input);
    return output!;
  }
);
